rvm:
- 1.9.3
- 2.0.0
- 2.1

env:
  global:
  - KITCHEN_ARGS="--concurrency=2 --destroy=always"
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
# CHEF_VERSION is only for unit tests, no for test-kitchen:
  - TESTS="style unit"  CHEF_VERSION="~> 11.0"
  - TESTS="style unit"  CHEF_VERSION="~> 12.0"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration" KITCHEN_REGEXP=default
  - TESTS="integration" KITCHEN_REGEXP=ldap-debian
  - TESTS="integration" KITCHEN_REGEXP=attributes

matrix:
  exclude:
  - rvm: 1.9.3
    env: TESTS="style unit"  CHEF_VERSION="~> 12.0"

bundler_args: --without doc integration_vagrant integration_cloud guard

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.1.0/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake $TESTS

after_failure: cat docker_daemon.log
